package id.ufal.localnhread;
import android.content.*; import android.graphics.Bitmap; import android.graphics.Typeface; import android.net.Uri; import android.os.Bundle; import android.text.SpannableStringBuilder; import android.text.Spanned; import android.text.style.StyleSpan; import android.view.View; import android.widget.*;
import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import androidx.core.graphics.Insets; import androidx.core.view.*; import androidx.recyclerview.widget.GridLayoutManager; import androidx.recyclerview.widget.RecyclerView; import java.io.File; import java.util.*; import java.util.concurrent.*;
public final class GalleryActivity extends AppCompatActivity {
    static final String URI="uri", MODIFIED="modified", ARCHIVE="archive", PAGES="pages", START="start"; private final ExecutorService worker=Executors.newSingleThreadExecutor(); private Uri uri; private long modified; private File archive; private Cartridge cartridge;
    @Override protected void onCreate(@Nullable Bundle state){super.onCreate(state);setContentView(R.layout.activity_gallery);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);View root=findViewById(R.id.galleryRoot);ViewCompat.setOnApplyWindowInsetsListener(root,(v,i)->{Insets b=i.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(b.left,b.top,b.right,b.bottom);return i;});uri=Uri.parse(getIntent().getStringExtra(URI));modified=getIntent().getLongExtra(MODIFIED,0);load();}
    private void load(){worker.execute(()->{try{archive=CartridgeArchive.cacheArchive(this,uri,modified);cartridge=CartridgeArchive.readCached(archive,uri,modified);ArrayList<Bitmap> previews=new ArrayList<>();for(String page:cartridge.pages)previews.add(CartridgeArchive.page(archive,page,360));runOnUiThread(()->show(previews));}catch(Exception e){runOnUiThread(()->{Toast.makeText(this,"could not open cartridge.",Toast.LENGTH_LONG).show();finish();});}});}
    private void show(ArrayList<Bitmap> previews){((ImageView)findViewById(R.id.galleryCover)).setImageBitmap(cartridge.cover);((TextView)findViewById(R.id.galleryTitle)).setText(cartridge.title);((TextView)findViewById(R.id.galleryId)).setText("#"+cartridge.id);((TextView)findViewById(R.id.galleryTags)).setText(withBoldLabels(cartridge.tagsText));String details="language   "+cartridge.language+"\npages   "+cartridge.pages.size()+"\nuploaded   "+cartridge.uploaded+"\narchived   "+cartridge.archived+(cartridge.scanlator.isEmpty()?"":"\nscanlator   "+cartridge.scanlator);((TextView)findViewById(R.id.galleryDetails)).setText(withBoldLabels(details));findViewById(R.id.readButton).setOnClickListener(v->openReader(0));RecyclerView grid=findViewById(R.id.previewGrid);grid.setLayoutManager(new GridLayoutManager(this,2));grid.setAdapter(new PreviewAdapter(previews,this::openReader));}
    private static CharSequence withBoldLabels(String text){SpannableStringBuilder result=new SpannableStringBuilder(text);int lineStart=0;while(lineStart<text.length()){int lineEnd=text.indexOf('\n',lineStart);if(lineEnd<0)lineEnd=text.length();int separator=text.indexOf("   ",lineStart);if(separator>=lineStart&&separator<lineEnd)result.setSpan(new StyleSpan(Typeface.BOLD),lineStart,separator,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);lineStart=lineEnd+1;}return result;}
    private void openReader(int start){Intent i=new Intent(this,ReaderActivity.class);i.putExtra(ARCHIVE,archive.getAbsolutePath());i.putStringArrayListExtra(PAGES,cartridge.pages);i.putExtra(START,start);startActivity(i);}
    @Override protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
