package id.ufal.localnhread;
import android.content.*; import android.net.Uri; import android.os.Bundle; import android.view.View; import android.widget.*;
import androidx.activity.result.*; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.Nullable; import androidx.appcompat.app.AppCompatActivity; import androidx.core.graphics.Insets; import androidx.core.view.*; import androidx.documentfile.provider.DocumentFile; import androidx.recyclerview.widget.GridLayoutManager; import androidx.recyclerview.widget.RecyclerView;
import java.util.*; import java.util.concurrent.*;
public final class MainActivity extends AppCompatActivity {
    private static final String PREF="library", TREE="tree"; private final ExecutorService worker=Executors.newSingleThreadExecutor(); private BookAdapter adapter; private TextView folder; private View empty; private Button rescan; private ActivityResultLauncher<Uri> picker;
    @Override protected void onCreate(@Nullable Bundle state){super.onCreate(state);setContentView(R.layout.activity_main);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);View root=findViewById(R.id.rootLayout);ViewCompat.setOnApplyWindowInsetsListener(root,(v,i)->{Insets b=i.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(b.left,b.top,b.right,b.bottom);return i;});
        adapter=new BookAdapter(this::open); RecyclerView list=findViewById(R.id.bookList);list.setLayoutManager(new GridLayoutManager(this,2));list.setAdapter(adapter);folder=findViewById(R.id.folderLabel);empty=findViewById(R.id.emptyState);rescan=findViewById(R.id.rescanButton);
        picker=registerForActivityResult(new ActivityResultContracts.OpenDocumentTree(),uri->{if(uri==null)return;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);prefs().edit().putString(TREE,uri.toString()).apply();scan();}catch(SecurityException e){Toast.makeText(this,R.string.folder_access_error,Toast.LENGTH_LONG).show();}});
        findViewById(R.id.chooseFolderButton).setOnClickListener(v->picker.launch(null));findViewById(R.id.changeFolderButton).setOnClickListener(v->picker.launch(null));rescan.setOnClickListener(v->scan());scan(); }
    private SharedPreferences prefs(){return getSharedPreferences(PREF,MODE_PRIVATE);} private void scan(){String saved=prefs().getString(TREE,null);if(saved==null){folder.setText("");empty.setVisibility(View.VISIBLE);rescan.setEnabled(false);return;} Uri uri=Uri.parse(saved);folder.setText("…");rescan.setEnabled(false);worker.execute(()->{ArrayList<Cartridge> items=new ArrayList<>();DocumentFile root=DocumentFile.fromTreeUri(this,uri);try{if(root!=null&&root.canRead()) collect(root,items);}catch(Exception ignored){}items.sort(Comparator.comparingLong((Cartridge c)->c.modified).reversed());runOnUiThread(()->{rescan.setEnabled(true);folder.setText(String.valueOf(items.size()));adapter.replace(items);empty.setVisibility(items.isEmpty()?View.VISIBLE:View.GONE);if(root==null||!root.canRead())Toast.makeText(this,R.string.folder_lost,Toast.LENGTH_LONG).show();});});}
    private void collect(DocumentFile dir,List<Cartridge> items){DocumentFile[] children;try{children=dir.listFiles();}catch(Exception ignored){return;}for(DocumentFile child:children){if(child.isDirectory())collect(child,items);else if(child.isFile()&&child.getName()!=null&&child.getName().toLowerCase().endsWith(".lnhc"))try{items.add(CartridgeArchive.inspect(this,child.getUri(),child.lastModified(),false));}catch(Exception ignored){}}}
    private void open(Cartridge c){Intent i=new Intent(this,GalleryActivity.class);i.putExtra(GalleryActivity.URI,c.uri.toString());i.putExtra(GalleryActivity.MODIFIED,c.modified);startActivity(i);} @Override protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
